### ISSUE TITLE
CloudFlare API not setting correct value

### ISSUE THREAD

**Issue by RoliSoft** [Neilpang/acme.sh#229]
I've been unable to use the DNS-01 challenge to update any of my domains on CloudFlare, as I just get "Correct value not found for DNS challenge". The records are in fact set, and this method *was* working last time I used it, now it does not seem to be cooperating correctly for any account/domain.

	$ acme.sh --test -k 4096 --issue --dns dns_cf -d rolisoft.net
	[Fri Jul  1 23:05:42 UTC 2016] Using stage api:https://acme-staging.api.letsencrypt.org
	[Fri Jul  1 23:05:43 UTC 2016] Skip register account key
	[Fri Jul  1 23:05:43 UTC 2016] Creating csr
	[Fri Jul  1 23:05:43 UTC 2016] Single domain='rolisoft.net'
	[Fri Jul  1 23:05:43 UTC 2016] Verify each domain
	[Fri Jul  1 23:05:43 UTC 2016] Getting webroot for domain='rolisoft.net'
	[Fri Jul  1 23:05:43 UTC 2016] Getting token for domain='rolisoft.net'
	[Fri Jul  1 23:05:45 UTC 2016] Found domain api file: /root/.acme.sh/dnsapi/dns_cf.sh
	[Fri Jul  1 23:05:47 UTC 2016] Adding record
	[Fri Jul  1 23:05:47 UTC 2016] Added, sleeping 10 seconds
	[Fri Jul  1 23:05:57 UTC 2016] Sleep 60 seconds for the txt records to take effect
	[Fri Jul  1 23:06:57 UTC 2016] Verifying:rolisoft.net
	[Fri Jul  1 23:07:04 UTC 2016] rolisoft.net:Verify error:Correct value not found for DNS challenge

**Comment by Neilpang** [comment]
Hi,
I just tried with one of my domain with cloudflare api.  It's working for me.

can you please upgrade to the latest version and try again?

```
curl https://get.acme.sh | sh
```

In future, you can use `--upgrade` command to upgrade.
```
acme.sh  --upgrade
```


If you still have problem,  please add `--debug 2` and paste the log here:

https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

**Comment by k0nsl** [comment]
I used the CloudFlare API on one of my domains and it worked fine. I went ahead to add another domain, but it fails, with the following message:
```
[Sat Jul  2 01:24:36 UTC 2016] Sign failed: "detail":"Invalid key in certificate request :: Key too large: 8192 \u003e 4096"
```

I tried setting `keylength` and `accountkeylength` and repeating the issue process, but just keeps failing and returning the error message above. Any idea how to fix it?

**Comment by Neilpang** [comment]
@k0nsl 

```
acme.sh  --issue    .....    --keylength 4096
```


If you still have problem, please add --debug 2 and paste the log here:

https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

**Comment by k0nsl** [comment]
@Neilpang: the `--keylength` flag would not change anything, almost as if it had no effect no matter what you put (eg: 2048, 3072, 4096 or 8192).

The only way to successfully "solve" it was to delete the entire directory in /root/.acme.sh/. For example if my domain was `ssl.k0nsl.org` it means I had to delete that directory. Re-running the acme.sh script results in success.

**Comment by Neilpang** [comment]
Hi @k0nsl 

Thanks for your info,  it was a bug,  I just fixed it   at  61623d22d81f6671c5820685069497a443a64152

The keylength  should work as expected now.

Thanks.

**Comment by k0nsl** [comment]
@Neilpang: Nice! Yeah I was just checking out the commit :)

Thank you.

**Comment by RoliSoft** [comment]
@Neilpang I was already on the latest version when opening the issue. However, after upgrading again, I was able to get the certificates issued.

Thank you!

**Comment by Nosxxx** [comment]
I have the same error, updating does not fix the error.

`acme.sh --keylength 4096 --issue --dns dns_cf -d lookup.fail --debug 2
https://github.com/Neilpang/acme.sh
v2.3.2
[Fr 15. Jul 16:00:00 CEST 2016] APP
[Fr 15. Jul 16:00:00 CEST 2016] /root/.acme.sh/lookup.fail/lookup.fail.conf:1:Le_Domain="lookup.fail"
[Fr 15. Jul 16:00:00 CEST 2016] APP
[Fr 15. Jul 16:00:00 CEST 2016] /root/.acme.sh/lookup.fail/lookup.fail.conf:2:Le_Alt="no"
[Fr 15. Jul 16:00:00 CEST 2016] APP
[Fr 15. Jul 16:00:00 CEST 2016] /root/.acme.sh/lookup.fail/lookup.fail.conf:3:Le_Webroot="dns_cf"
[Fr 15. Jul 16:00:00 CEST 2016] 'dns_cf' does not contain 'no'
[Fr 15. Jul 16:00:00 CEST 2016] 'dns_cf' does not contain 'tls'
[Fr 15. Jul 16:00:00 CEST 2016] 'dns_cf' does not contain 'apache'
[Fr 15. Jul 16:00:00 CEST 2016] RSA key
[Fr 15. Jul 16:00:00 CEST 2016] pub_exp='010001'
[Fr 15. Jul 16:00:00 CEST 2016] let exists=0
[Fr 15. Jul 16:00:00 CEST 2016] uselet='1'
[Fr 15. Jul 16:00:00 CEST 2016] _URGLY_PRINTF
[Fr 15. Jul 16:00:00 CEST 2016] e='AQAB'
[Fr 15. Jul 16:00:00 CEST 2016] modulus='C1698B90098F6964FA06539647F0FB9E2547FE3B4DFA3141F4B66DFAFB4BD4C1F88BEF5EF09EDC9542DFC6E84174B8D20C05C61098417A778D690AA2ED7893FAD16639698634DD1FD2CD05EF3AC5515EC85C6061461B8BDE18F68D287BDC2A775969FD840EBEB4F6DE6D47E37042F56E62DCAD675397240FA2C03FECE363516ED96215254F431F5C3B5CEEF8C5C8121DCA32F7F6C31572830052E997E17E7173B84B929F3ABC25D691636DC595B2AC6E70DAE7C254B998A7A307F03F8E7C16C5D07DA354EB48DFD3A7E342A6EDC57F783379A3AD50DA82BED5AFD71526345758F60FBEFE3001D08108C34FD127188A9C48C806BB9F981045EECACC0000CF61EB'
[Fr 15. Jul 16:00:00 CEST 2016] let exists=0
[Fr 15. Jul 16:00:00 CEST 2016] uselet='1'
[Fr 15. Jul 16:00:00 CEST 2016] _URGLY_PRINTF
[Fr 15. Jul 16:00:01 CEST 2016] jwk='{"e": "AQAB", "kty": "RSA", "n": "wWmLkAmPaWT6BlOWR_D7niVH_jtN-jFB9LZt-vtL1MH4i-9e8J7clULfxuhBdLjSDAXGEJhBeneNaQqi7XiT-tFmOWmGNN0f0s0F7zrFUV7IXGBhRhuL3hj2jSh73Cp3WWn9hA6-tPbebUfjcEL1bmLcrWdTlyQPosA_7ONjUW7ZYhUlT0MfXDtc7vjFyBIdyjL39sMVcoMAUumX4X5xc7hLkp86vCXWkWNtxZWyrG5w2ufCVLmYp6MH8D-OfBbF0H2jVOtI39On40Km7cV_eDN5o61Q2oK-1a_XFSY0V1j2D77-MAHQgQjDT9EnGIqcSMgGu5-YEEXuyswAAM9h6w"}'
[Fr 15. Jul 16:00:01 CEST 2016] HEADER='{"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "wWmLkAmPaWT6BlOWR_D7niVH_jtN-jFB9LZt-vtL1MH4i-9e8J7clULfxuhBdLjSDAXGEJhBeneNaQqi7XiT-tFmOWmGNN0f0s0F7zrFUV7IXGBhRhuL3hj2jSh73Cp3WWn9hA6-tPbebUfjcEL1bmLcrWdTlyQPosA_7ONjUW7ZYhUlT0MfXDtc7vjFyBIdyjL39sMVcoMAUumX4X5xc7hLkp86vCXWkWNtxZWyrG5w2ufCVLmYp6MH8D-OfBbF0H2jVOtI39On40Km7cV_eDN5o61Q2oK-1a_XFSY0V1j2D77-MAHQgQjDT9EnGIqcSMgGu5-YEEXuyswAAM9h6w"}}'
[Fr 15. Jul 16:00:01 CEST 2016] Skip register account key
[Fr 15. Jul 16:00:01 CEST 2016] Read key length:4096
[Fr 15. Jul 16:00:01 CEST 2016] Creating domain key
[Fr 15. Jul 16:00:01 CEST 2016] Use length 4096
[Fr 15. Jul 16:00:02 CEST 2016] APP
[Fr 15. Jul 16:00:02 CEST 2016] /root/.acme.sh/lookup.fail/lookup.fail.conf:4:Le_Keylength="4096"
[Fr 15. Jul 16:00:02 CEST 2016] Creating csr
[Fr 15. Jul 16:00:02 CEST 2016] _createcsr
[Fr 15. Jul 16:00:02 CEST 2016] domain='lookup.fail'
[Fr 15. Jul 16:00:02 CEST 2016] domainlist
[Fr 15. Jul 16:00:02 CEST 2016] Single domain='lookup.fail'
[Fr 15. Jul 16:00:02 CEST 2016] Verify each domain
[Fr 15. Jul 16:00:02 CEST 2016] Getting webroot for domain='lookup.fail'
[Fr 15. Jul 16:00:02 CEST 2016] _w='dns_cf'
[Fr 15. Jul 16:00:02 CEST 2016] _currentRoot='dns_cf'
[Fr 15. Jul 16:00:02 CEST 2016] Getting token for domain='lookup.fail'
[Fr 15. Jul 16:00:02 CEST 2016] url='https://acme-v01.api.letsencrypt.org/acme/new-authz'
[Fr 15. Jul 16:00:02 CEST 2016] payload='{"resource": "new-authz", "identifier": {"type": "dns", "value": "lookup.fail"}}'
[Fr 15. Jul 16:00:02 CEST 2016] RSA key
[Fr 15. Jul 16:00:02 CEST 2016] pub_exp='010001'
[Fr 15. Jul 16:00:02 CEST 2016] let exists=0
[Fr 15. Jul 16:00:02 CEST 2016] uselet='1'
[Fr 15. Jul 16:00:02 CEST 2016] _URGLY_PRINTF
[Fr 15. Jul 16:00:02 CEST 2016] e='AQAB'
[Fr 15. Jul 16:00:02 CEST 2016] modulus='C1698B90098F6964FA06539647F0FB9E2547FE3B4DFA3141F4B66DFAFB4BD4C1F88BEF5EF09EDC9542DFC6E84174B8D20C05C61098417A778D690AA2ED7893FAD16639698634DD1FD2CD05EF3AC5515EC85C6061461B8BDE18F68D287BDC2A775969FD840EBEB4F6DE6D47E37042F56E62DCAD675397240FA2C03FECE363516ED96215254F431F5C3B5CEEF8C5C8121DCA32F7F6C31572830052E997E17E7173B84B929F3ABC25D691636DC595B2AC6E70DAE7C254B998A7A307F03F8E7C16C5D07DA354EB48DFD3A7E342A6EDC57F783379A3AD50DA82BED5AFD71526345758F60FBEFE3001D08108C34FD127188A9C48C806BB9F981045EECACC0000CF61EB'
[Fr 15. Jul 16:00:02 CEST 2016] let exists=0
[Fr 15. Jul 16:00:02 CEST 2016] uselet='1'
[Fr 15. Jul 16:00:02 CEST 2016] _URGLY_PRINTF
[Fr 15. Jul 16:00:03 CEST 2016] jwk='{"e": "AQAB", "kty": "RSA", "n": "wWmLkAmPaWT6BlOWR_D7niVH_jtN-jFB9LZt-vtL1MH4i-9e8J7clULfxuhBdLjSDAXGEJhBeneNaQqi7XiT-tFmOWmGNN0f0s0F7zrFUV7IXGBhRhuL3hj2jSh73Cp3WWn9hA6-tPbebUfjcEL1bmLcrWdTlyQPosA_7ONjUW7ZYhUlT0MfXDtc7vjFyBIdyjL39sMVcoMAUumX4X5xc7hLkp86vCXWkWNtxZWyrG5w2ufCVLmYp6MH8D-OfBbF0H2jVOtI39On40Km7cV_eDN5o61Q2oK-1a_XFSY0V1j2D77-MAHQgQjDT9EnGIqcSMgGu5-YEEXuyswAAM9h6w"}'
[Fr 15. Jul 16:00:03 CEST 2016] HEADER='{"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "wWmLkAmPaWT6BlOWR_D7niVH_jtN-jFB9LZt-vtL1MH4i-9e8J7clULfxuhBdLjSDAXGEJhBeneNaQqi7XiT-tFmOWmGNN0f0s0F7zrFUV7IXGBhRhuL3hj2jSh73Cp3WWn9hA6-tPbebUfjcEL1bmLcrWdTlyQPosA_7ONjUW7ZYhUlT0MfXDtc7vjFyBIdyjL39sMVcoMAUumX4X5xc7hLkp86vCXWkWNtxZWyrG5w2ufCVLmYp6MH8D-OfBbF0H2jVOtI39On40Km7cV_eDN5o61Q2oK-1a_XFSY0V1j2D77-MAHQgQjDT9EnGIqcSMgGu5-YEEXuyswAAM9h6w"}}'
[Fr 15. Jul 16:00:03 CEST 2016] payload64='eyJyZXNvdXJjZSI6ICJuZXctYXV0aHoiLCAiaWRlbnRpZmllciI6IHsidHlwZSI6ICJkbnMiLCAidmFsdWUiOiAibG9va3VwLmZhaWwifX0'
[Fr 15. Jul 16:00:03 CEST 2016] GET
[Fr 15. Jul 16:00:03 CEST 2016] url='https://acme-v01.api.letsencrypt.org/directory'
[Fr 15. Jul 16:00:03 CEST 2016] curl exists=0
[Fr 15. Jul 16:00:03 CEST 2016] CURL='curl -L --silent --trace-ascii /root/.acme.sh/curl.dump '
[Fr 15. Jul 16:00:03 CEST 2016] ret='0'
[Fr 15. Jul 16:00:03 CEST 2016] _headers='HTTP/1.1 200 OK
Server: nginx
Content-Type: application/json
Content-Length: 280
Boulder-Request-Id: 6yGntHYbjW1myI_w-RN_UdtOMo6iuZAQsgS0YZJIQzs
Replay-Nonce: T9jrvqb0kAQ5qG2wLcm1T1VUu3CnoC9TETl-jOFfdQ8
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Fri, 15 Jul 2016 14:00:03 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 15 Jul 2016 14:00:03 GMT
Connection: keep-alive
'
[Fr 15. Jul 16:00:03 CEST 2016] nonce='T9jrvqb0kAQ5qG2wLcm1T1VUu3CnoC9TETl-jOFfdQ8'
[Fr 15. Jul 16:00:03 CEST 2016] protected='{"nonce": "T9jrvqb0kAQ5qG2wLcm1T1VUu3CnoC9TETl-jOFfdQ8", "alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "wWmLkAmPaWT6BlOWR_D7niVH_jtN-jFB9LZt-vtL1MH4i-9e8J7clULfxuhBdLjSDAXGEJhBeneNaQqi7XiT-tFmOWmGNN0f0s0F7zrFUV7IXGBhRhuL3hj2jSh73Cp3WWn9hA6-tPbebUfjcEL1bmLcrWdTlyQPosA_7ONjUW7ZYhUlT0MfXDtc7vjFyBIdyjL39sMVcoMAUumX4X5xc7hLkp86vCXWkWNtxZWyrG5w2ufCVLmYp6MH8D-OfBbF0H2jVOtI39On40Km7cV_eDN5o61Q2oK-1a_XFSY0V1j2D77-MAHQgQjDT9EnGIqcSMgGu5-YEEXuyswAAM9h6w"}}'
[Fr 15. Jul 16:00:03 CEST 2016] protected64='eyJub25jZSI6ICJUOWpydnFiMGtBUTVxRzJ3TGNtMVQxVlV1M0Nub0M5VEVUbC1qT0ZmZFE4IiwgImFsZyI6ICJSUzI1NiIsICJqd2siOiB7ImUiOiAiQVFBQiIsICJrdHkiOiAiUlNBIiwgIm4iOiAid1dtTGtBbVBhV1Q2QmxPV1JfRDduaVZIX2p0Ti1qRkI5TFp0LXZ0TDFNSDRpLTllOEo3Y2xVTGZ4dWhCZExqU0RBWEdFSmhCZW5lTmFRcWk3WGlULXRGbU9XbUdOTjBmMHMwRjd6ckZVVjdJWEdCaFJodUwzaGoyalNoNzNDcDNXV245aEE2LXRQYmViVWZqY0VMMWJtTGNyV2RUbHlRUG9zQV83T05qVVc3WlloVWxUME1mWER0Yzd2akZ5QklkeWpMMzlzTVZjb01BVXVtWDRYNXhjN2hMa3A4NnZDWFdrV050eFpXeXJHNXcydWZDVkxtWXA2TUg4RC1PZkJiRjBIMmpWT3RJMzlPbjQwS203Y1ZfZURONW82MVEyb0stMWFfWEZTWTBWMWoyRDc3LU1BSFFnUWpEVDlFbkdJcWNTTWdHdTUtWUVFWHV5c3dBQU05aDZ3In19'
[Fr 15. Jul 16:00:03 CEST 2016] sig='o-9XI25y8ClRVni3D0Fg4OP02rskofz0JetXeqmtl_E2mv2cM1cQtojoRlw3kIR4A1-YctEmvTPm7jljNxc526VuGkAF5a5PptkXbqbSh3zf2Y7j6hwnrzk1TZgbLQZz8e71BGL00af4C0TvECzT97BaYb2-rxmXzvbsuuiYVFS916UgYfgSFuqPEgVcBNsnrQ5MsHQVvdOEtoujOJYKl5LjPbZMZr_-rMq6AYCtoi_rBzs7-n6ihZ3_ZdhdxGeAK5utD5d_1sWZuTh2yD2bFqnDW5FABUQRJ1B7LrxIl8OZnhP6_l3oxV0iZgvDwqhG38mX_0ocJ98L1i13sl45Kg'
[Fr 15. Jul 16:00:03 CEST 2016] body='{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "wWmLkAmPaWT6BlOWR_D7niVH_jtN-jFB9LZt-vtL1MH4i-9e8J7clULfxuhBdLjSDAXGEJhBeneNaQqi7XiT-tFmOWmGNN0f0s0F7zrFUV7IXGBhRhuL3hj2jSh73Cp3WWn9hA6-tPbebUfjcEL1bmLcrWdTlyQPosA_7ONjUW7ZYhUlT0MfXDtc7vjFyBIdyjL39sMVcoMAUumX4X5xc7hLkp86vCXWkWNtxZWyrG5w2ufCVLmYp6MH8D-OfBbF0H2jVOtI39On40Km7cV_eDN5o61Q2oK-1a_XFSY0V1j2D77-MAHQgQjDT9EnGIqcSMgGu5-YEEXuyswAAM9h6w"}}, "protected": "eyJub25jZSI6ICJUOWpydnFiMGtBUTVxRzJ3TGNtMVQxVlV1M0Nub0M5VEVUbC1qT0ZmZFE4IiwgImFsZyI6ICJSUzI1NiIsICJqd2siOiB7ImUiOiAiQVFBQiIsICJrdHkiOiAiUlNBIiwgIm4iOiAid1dtTGtBbVBhV1Q2QmxPV1JfRDduaVZIX2p0Ti1qRkI5TFp0LXZ0TDFNSDRpLTllOEo3Y2xVTGZ4dWhCZExqU0RBWEdFSmhCZW5lTmFRcWk3WGlULXRGbU9XbUdOTjBmMHMwRjd6ckZVVjdJWEdCaFJodUwzaGoyalNoNzNDcDNXV245aEE2LXRQYmViVWZqY0VMMWJtTGNyV2RUbHlRUG9zQV83T05qVVc3WlloVWxUME1mWER0Yzd2akZ5QklkeWpMMzlzTVZjb01BVXVtWDRYNXhjN2hMa3A4NnZDWFdrV050eFpXeXJHNXcydWZDVkxtWXA2TUg4RC1PZkJiRjBIMmpWT3RJMzlPbjQwS203Y1ZfZURONW82MVEyb0stMWFfWEZTWTBWMWoyRDc3LU1BSFFnUWpEVDlFbkdJcWNTTWdHdTUtWUVFWHV5c3dBQU05aDZ3In19", "payload": "eyJyZXNvdXJjZSI6ICJuZXctYXV0aHoiLCAiaWRlbnRpZmllciI6IHsidHlwZSI6ICJkbnMiLCAidmFsdWUiOiAibG9va3VwLmZhaWwifX0", "signature": "o-9XI25y8ClRVni3D0Fg4OP02rskofz0JetXeqmtl_E2mv2cM1cQtojoRlw3kIR4A1-YctEmvTPm7jljNxc526VuGkAF5a5PptkXbqbSh3zf2Y7j6hwnrzk1TZgbLQZz8e71BGL00af4C0TvECzT97BaYb2-rxmXzvbsuuiYVFS916UgYfgSFuqPEgVcBNsnrQ5MsHQVvdOEtoujOJYKl5LjPbZMZr_-rMq6AYCtoi_rBzs7-n6ihZ3_ZdhdxGeAK5utD5d_1sWZuTh2yD2bFqnDW5FABUQRJ1B7LrxIl8OZnhP6_l3oxV0iZgvDwqhG38mX_0ocJ98L1i13sl45Kg"}'
[Fr 15. Jul 16:00:03 CEST 2016] POST
[Fr 15. Jul 16:00:03 CEST 2016] url='https://acme-v01.api.letsencrypt.org/acme/new-authz'
[Fr 15. Jul 16:00:03 CEST 2016] curl exists=0
[Fr 15. Jul 16:00:03 CEST 2016] _CURL='curl -L --silent --trace-ascii /root/.acme.sh/curl.dump  --dump-header /root/.acme.sh/http.header '
[Fr 15. Jul 16:00:03 CEST 2016] _ret='0'
[Fr 15. Jul 16:00:03 CEST 2016] original='{
  "identifier": {
    "type": "dns",
    "value": "lookup.fail"
  },
  "status": "pending",
  "expires": "2016-07-22T14:00:03.892440981Z",
  "challenges": [
    {
      "type": "tls-sni-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/BhTZROHFCuTBjIi0ZwiP5g-ArE4oIuV4vLbVo0g10B4/176495505",
      "token": "_6b5wilnS2pRLjfqNA2Dn18EsE6HsYZvDuKEWTM3xpU"
    },
    {
      "type": "http-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/BhTZROHFCuTBjIi0ZwiP5g-ArE4oIuV4vLbVo0g10B4/176495506",
      "token": "TGszgTmHnGtkbcyip1nTnGsXns9uhvlxujvJZ0-f_dw"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/BhTZROHFCuTBjIi0ZwiP5g-ArE4oIuV4vLbVo0g10B4/176495507",
      "token": "jVoiVSGNzIuNnUXycdx7-dci-4kb6dZeTaypGsS7sRw"
    }
  ],
  "combinations": [
    [
      1
    ],
    [
      2
    ],
    [
      0
    ]
  ]
}'
[Fr 15. Jul 16:00:03 CEST 2016] responseHeaders='HTTP/1.1 100 Continue
Expires: Fri, 15 Jul 2016 14:00:03 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache

HTTP/1.1 201 Created
Server: nginx
Content-Type: application/json
Content-Length: 996
Boulder-Request-Id: JMiUXLxs6GfR9wcJxIOmlWqNlbwk3lGC4J3JEbxNvJ0
Boulder-Requester: 2632158
Link: <https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"
Location: https://acme-v01.api.letsencrypt.org/acme/authz/BhTZROHFCuTBjIi0ZwiP5g-ArE4oIuV4vLbVo0g10B4
Replay-Nonce: WEwDRnPcSaNa6fkgUgJxwOp4CXVWedwUIQkkAdVmKd4
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Fri, 15 Jul 2016 14:00:03 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 15 Jul 2016 14:00:03 GMT
Connection: keep-alive
'
[Fr 15. Jul 16:00:04 CEST 2016] response='{"identifier":{"type":"dns","value":"lookup.fail"},"status":"pending","expires":"2016-07-22T14:00:03.892440981Z","challenges":[{"type":"tls-sni-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/BhTZROHFCuTBjIi0ZwiP5g-ArE4oIuV4vLbVo0g10B4/176495505","token":"_6b5wilnS2pRLjfqNA2Dn18EsE6HsYZvDuKEWTM3xpU"},{"type":"http-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/BhTZROHFCuTBjIi0ZwiP5g-ArE4oIuV4vLbVo0g10B4/176495506","token":"TGszgTmHnGtkbcyip1nTnGsXns9uhvlxujvJZ0-f_dw"},{"type":"dns-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/BhTZROHFCuTBjIi0ZwiP5g-ArE4oIuV4vLbVo0g10B4/176495507","token":"jVoiVSGNzIuNnUXycdx7-dci-4kb6dZeTaypGsS7sRw"}],"combinations":[[1],[2],[0]]}'
[Fr 15. Jul 16:00:04 CEST 2016] code='201'
[Fr 15. Jul 16:00:04 CEST 2016] entry='{"type":"dns-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/BhTZROHFCuTBjIi0ZwiP5g-ArE4oIuV4vLbVo0g10B4/176495507","token":"jVoiVSGNzIuNnUXycdx7-dci-4kb6dZeTaypGsS7sRw"'
[Fr 15. Jul 16:00:04 CEST 2016] token='jVoiVSGNzIuNnUXycdx7-dci-4kb6dZeTaypGsS7sRw'
[Fr 15. Jul 16:00:04 CEST 2016] uri='https://acme-v01.api.letsencrypt.org/acme/challenge/BhTZROHFCuTBjIi0ZwiP5g-ArE4oIuV4vLbVo0g10B4/176495507'
[Fr 15. Jul 16:00:04 CEST 2016] keyauthorization='jVoiVSGNzIuNnUXycdx7-dci-4kb6dZeTaypGsS7sRw.F2Hoae3GiC4eT8d5Vjk6vtwxVlGzkhA-cO7Gtb3yns8'
[Fr 15. Jul 16:00:04 CEST 2016] dvlist='lookup.fail#jVoiVSGNzIuNnUXycdx7-dci-4kb6dZeTaypGsS7sRw.F2Hoae3GiC4eT8d5Vjk6vtwxVlGzkhA-cO7Gtb3yns8#https://acme-v01.api.letsencrypt.org/acme/challenge/BhTZROHFCuTBjIi0ZwiP5g-ArE4oIuV4vLbVo0g10B4/176495507#dns-01#dns_cf'
[Fr 15. Jul 16:00:04 CEST 2016] txtdomain='_acme-challenge.lookup.fail'
[Fr 15. Jul 16:00:04 CEST 2016] txt='CwWRF0kiHlLAsXp1xubtVqjuWuAWxEngsau_HMNBLr8'
[Fr 15. Jul 16:00:04 CEST 2016] d_api='/root/.acme.sh/dnsapi/dns_cf.sh'
[Fr 15. Jul 16:00:04 CEST 2016] Found domain api file: /root/.acme.sh/dnsapi/dns_cf.sh
[Fr 15. Jul 16:00:04 CEST 2016] dns_cf_add exists=0
[Fr 15. Jul 16:00:04 CEST 2016] OK
[Fr 15. Jul 16:00:04 CEST 2016] /root/.acme.sh/account.conf:24:CF_Key="9486e2e8966f74fe8bb150dd6ac975b5b1d57"
[Fr 15. Jul 16:00:04 CEST 2016] OK
[Fr 15. Jul 16:00:04 CEST 2016] /root/.acme.sh/account.conf:26:CF_Email="roman.krautgartner@outlook.com"
[Fr 15. Jul 16:00:04 CEST 2016] First detect the root zone
[Fr 15. Jul 16:00:04 CEST 2016] zones?name=lookup.fail
[Fr 15. Jul 16:00:04 CEST 2016] GET
[Fr 15. Jul 16:00:04 CEST 2016] url='https://api.cloudflare.com/client/v4/zones?name=lookup.fail'
[Fr 15. Jul 16:00:04 CEST 2016] curl exists=0
[Fr 15. Jul 16:00:04 CEST 2016] CURL='curl -L --silent --trace-ascii /root/.acme.sh/curl.dump '
[Fr 15. Jul 16:00:06 CEST 2016] ret='0'
[Fr 15. Jul 16:00:06 CEST 2016] response='{"result":[{"id":"77aa028eac4f7f980400473459085389","name":"lookup.fail","status":"active","paused":false,"type":"full","development_mode":0,"name_servers":["nina.ns.cloudflare.com","sid.ns.cloudflare.com"],"original_name_servers":["a.ns14.net","b.ns14.net","c.ns14.net","d.ns14.net"],"original_registrar":null,"original_dnshost":null,"modified_on":"2016-02-29T20:20:14.438544Z","created_on":"2016-01-07T14:29:22.897903Z","meta":{"step":4,"wildcard_proxiable":false,"custom_certificate_quota":0,"page_rule_quota":3,"phishing_detected":false,"multiple_railguns_allowed":false},"owner":{"type":"user","id":"4973fa0ec693a8c245c0878e4e67ec6f","email":"roman.krautgartner@outlook.com"},"permissions":["#analytics:read","#billing:edit","#billing:read","#cache_purge:edit","#dns_records:edit","#dns_records:read","#lb:edit","#lb:read","#logs:read","#organization:edit","#organization:read","#ssl:edit","#ssl:read","#waf:edit","#waf:read","#zone:edit","#zone:read","#zone_settings:edit","#zone_settings:read"],"plan":{"id":"0feeeeeeeeeeeeeeeeeeeeeeeeeeeeee","name":"Free Website","price":0,"currency":"USD","frequency":"","legacy_id":"free","legacy_discount":false,"is_subscribed":null,"can_subscribe":null,"externally_managed":false}}],"result_info":{"page":1,"per_page":20,"total_pages":1,"count":1,"total_count":1},"success":true,"errors":[],"messages":[]}'
[Fr 15. Jul 16:00:06 CEST 2016] _domain_id='77aa028eac4f7f980400473459085389'
[Fr 15. Jul 16:00:06 CEST 2016] _sub_domain='_acme-challenge'
[Fr 15. Jul 16:00:06 CEST 2016] _domain='lookup.fail'
[Fr 15. Jul 16:00:06 CEST 2016] Getting txt records
[Fr 15. Jul 16:00:06 CEST 2016] zones/77aa028eac4f7f980400473459085389/dns_records?type=TXT&name=_acme-challenge.lookup.fail
[Fr 15. Jul 16:00:06 CEST 2016] GET
[Fr 15. Jul 16:00:06 CEST 2016] url='https://api.cloudflare.com/client/v4/zones/77aa028eac4f7f980400473459085389/dns_records?type=TXT&name=_acme-challenge.lookup.fail'
[Fr 15. Jul 16:00:06 CEST 2016] curl exists=0
[Fr 15. Jul 16:00:06 CEST 2016] CURL='curl -L --silent --trace-ascii /root/.acme.sh/curl.dump '
[Fr 15. Jul 16:00:08 CEST 2016] ret='0'
[Fr 15. Jul 16:00:08 CEST 2016] response='{"result":[],"result_info":{"page":1,"per_page":20,"total_pages":0,"count":0,"total_count":0},"success":true,"errors":[],"messages":[]}'
[Fr 15. Jul 16:00:08 CEST 2016] count='0'
[Fr 15. Jul 16:00:08 CEST 2016] Adding record
[Fr 15. Jul 16:00:08 CEST 2016] zones/77aa028eac4f7f980400473459085389/dns_records
[Fr 15. Jul 16:00:08 CEST 2016] data='{"type":"TXT","name":"_acme-challenge.lookup.fail","content":"CwWRF0kiHlLAsXp1xubtVqjuWuAWxEngsau_HMNBLr8","ttl":120}'
[Fr 15. Jul 16:00:08 CEST 2016] POST
[Fr 15. Jul 16:00:08 CEST 2016] url='https://api.cloudflare.com/client/v4/zones/77aa028eac4f7f980400473459085389/dns_records'
[Fr 15. Jul 16:00:08 CEST 2016] curl exists=0
[Fr 15. Jul 16:00:08 CEST 2016] _CURL='curl -L --silent --trace-ascii /root/.acme.sh/curl.dump  --dump-header /root/.acme.sh/http.header '
[Fr 15. Jul 16:00:11 CEST 2016] _ret='0'
[Fr 15. Jul 16:00:11 CEST 2016] response='{"result":{"id":"ca49ce69a1ed3f1082e7288bba675416","type":"TXT","name":"_acme-challenge.lookup.fail","content":"CwWRF0kiHlLAsXp1xubtVqjuWuAWxEngsau_HMNBLr8","proxiable":false,"proxied":false,"ttl":120,"locked":false,"zone_id":"77aa028eac4f7f980400473459085389","zone_name":"lookup.fail","modified_on":"2016-07-15T14:00:11.336836Z","created_on":"2016-07-15T14:00:11.336836Z","meta":{"auto_added":false}},"success":true,"errors":[],"messages":[]}'
[Fr 15. Jul 16:00:11 CEST 2016] Added, sleeping 10 seconds
[Fr 15. Jul 16:00:21 CEST 2016] Sleep 60 seconds for the txt records to take effect
[Fr 15. Jul 16:01:21 CEST 2016] ok, let's start to verify
[Fr 15. Jul 16:01:21 CEST 2016] Verifying:lookup.fail
[Fr 15. Jul 16:01:21 CEST 2016] d='lookup.fail'
[Fr 15. Jul 16:01:21 CEST 2016] keyauthorization='jVoiVSGNzIuNnUXycdx7-dci-4kb6dZeTaypGsS7sRw.F2Hoae3GiC4eT8d5Vjk6vtwxVlGzkhA-cO7Gtb3yns8'
[Fr 15. Jul 16:01:21 CEST 2016] uri='https://acme-v01.api.letsencrypt.org/acme/challenge/BhTZROHFCuTBjIi0ZwiP5g-ArE4oIuV4vLbVo0g10B4/176495507'
[Fr 15. Jul 16:01:21 CEST 2016] _currentRoot='dns_cf'
[Fr 15. Jul 16:01:21 CEST 2016] url='https://acme-v01.api.letsencrypt.org/acme/challenge/BhTZROHFCuTBjIi0ZwiP5g-ArE4oIuV4vLbVo0g10B4/176495507'
[Fr 15. Jul 16:01:21 CEST 2016] payload='{"resource": "challenge", "keyAuthorization": "jVoiVSGNzIuNnUXycdx7-dci-4kb6dZeTaypGsS7sRw.F2Hoae3GiC4eT8d5Vjk6vtwxVlGzkhA-cO7Gtb3yns8"}'
[Fr 15. Jul 16:01:21 CEST 2016] RSA key
[Fr 15. Jul 16:01:21 CEST 2016] pub_exp='010001'
[Fr 15. Jul 16:01:21 CEST 2016] let exists=0
[Fr 15. Jul 16:01:21 CEST 2016] uselet='1'
[Fr 15. Jul 16:01:21 CEST 2016] _URGLY_PRINTF
[Fr 15. Jul 16:01:21 CEST 2016] e='AQAB'
[Fr 15. Jul 16:01:21 CEST 2016] modulus='C1698B90098F6964FA06539647F0FB9E2547FE3B4DFA3141F4B66DFAFB4BD4C1F88BEF5EF09EDC9542DFC6E84174B8D20C05C61098417A778D690AA2ED7893FAD16639698634DD1FD2CD05EF3AC5515EC85C6061461B8BDE18F68D287BDC2A775969FD840EBEB4F6DE6D47E37042F56E62DCAD675397240FA2C03FECE363516ED96215254F431F5C3B5CEEF8C5C8121DCA32F7F6C31572830052E997E17E7173B84B929F3ABC25D691636DC595B2AC6E70DAE7C254B998A7A307F03F8E7C16C5D07DA354EB48DFD3A7E342A6EDC57F783379A3AD50DA82BED5AFD71526345758F60FBEFE3001D08108C34FD127188A9C48C806BB9F981045EECACC0000CF61EB'
[Fr 15. Jul 16:01:21 CEST 2016] let exists=0
[Fr 15. Jul 16:01:21 CEST 2016] uselet='1'
[Fr 15. Jul 16:01:21 CEST 2016] _URGLY_PRINTF
[Fr 15. Jul 16:01:22 CEST 2016] jwk='{"e": "AQAB", "kty": "RSA", "n": "wWmLkAmPaWT6BlOWR_D7niVH_jtN-jFB9LZt-vtL1MH4i-9e8J7clULfxuhBdLjSDAXGEJhBeneNaQqi7XiT-tFmOWmGNN0f0s0F7zrFUV7IXGBhRhuL3hj2jSh73Cp3WWn9hA6-tPbebUfjcEL1bmLcrWdTlyQPosA_7ONjUW7ZYhUlT0MfXDtc7vjFyBIdyjL39sMVcoMAUumX4X5xc7hLkp86vCXWkWNtxZWyrG5w2ufCVLmYp6MH8D-OfBbF0H2jVOtI39On40Km7cV_eDN5o61Q2oK-1a_XFSY0V1j2D77-MAHQgQjDT9EnGIqcSMgGu5-YEEXuyswAAM9h6w"}'
[Fr 15. Jul 16:01:22 CEST 2016] HEADER='{"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "wWmLkAmPaWT6BlOWR_D7niVH_jtN-jFB9LZt-vtL1MH4i-9e8J7clULfxuhBdLjSDAXGEJhBeneNaQqi7XiT-tFmOWmGNN0f0s0F7zrFUV7IXGBhRhuL3hj2jSh73Cp3WWn9hA6-tPbebUfjcEL1bmLcrWdTlyQPosA_7ONjUW7ZYhUlT0MfXDtc7vjFyBIdyjL39sMVcoMAUumX4X5xc7hLkp86vCXWkWNtxZWyrG5w2ufCVLmYp6MH8D-OfBbF0H2jVOtI39On40Km7cV_eDN5o61Q2oK-1a_XFSY0V1j2D77-MAHQgQjDT9EnGIqcSMgGu5-YEEXuyswAAM9h6w"}}'
[Fr 15. Jul 16:01:22 CEST 2016] payload64='eyJyZXNvdXJjZSI6ICJjaGFsbGVuZ2UiLCAia2V5QXV0aG9yaXphdGlvbiI6ICJqVm9pVlNHTnpJdU5uVVh5Y2R4Ny1kY2ktNGtiNmRaZVRheXBHc1M3c1J3LkYySG9hZTNHaUM0ZVQ4ZDVWams2dnR3eFZsR3praEEtY083R3RiM3luczgifQ'
[Fr 15. Jul 16:01:22 CEST 2016] GET
[Fr 15. Jul 16:01:22 CEST 2016] url='https://acme-v01.api.letsencrypt.org/directory'
[Fr 15. Jul 16:01:22 CEST 2016] curl exists=0
[Fr 15. Jul 16:01:22 CEST 2016] CURL='curl -L --silent --trace-ascii /root/.acme.sh/curl.dump '
[Fr 15. Jul 16:01:22 CEST 2016] ret='0'
[Fr 15. Jul 16:01:22 CEST 2016] _headers='HTTP/1.1 200 OK
Server: nginx
Content-Type: application/json
Content-Length: 280
Boulder-Request-Id: VdxR7qpCDyMapsuRgB1UCniD7HKgiDdLRe0Q4yU9zBc
Replay-Nonce: hAU31V-v8YbNxbPf5CUu4NFLuP2zhQKRWLGIslzXSgk
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Fri, 15 Jul 2016 14:01:22 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 15 Jul 2016 14:01:22 GMT
Connection: keep-alive
'
[Fr 15. Jul 16:01:22 CEST 2016] nonce='hAU31V-v8YbNxbPf5CUu4NFLuP2zhQKRWLGIslzXSgk'
[Fr 15. Jul 16:01:22 CEST 2016] protected='{"nonce": "hAU31V-v8YbNxbPf5CUu4NFLuP2zhQKRWLGIslzXSgk", "alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "wWmLkAmPaWT6BlOWR_D7niVH_jtN-jFB9LZt-vtL1MH4i-9e8J7clULfxuhBdLjSDAXGEJhBeneNaQqi7XiT-tFmOWmGNN0f0s0F7zrFUV7IXGBhRhuL3hj2jSh73Cp3WWn9hA6-tPbebUfjcEL1bmLcrWdTlyQPosA_7ONjUW7ZYhUlT0MfXDtc7vjFyBIdyjL39sMVcoMAUumX4X5xc7hLkp86vCXWkWNtxZWyrG5w2ufCVLmYp6MH8D-OfBbF0H2jVOtI39On40Km7cV_eDN5o61Q2oK-1a_XFSY0V1j2D77-MAHQgQjDT9EnGIqcSMgGu5-YEEXuyswAAM9h6w"}}'
[Fr 15. Jul 16:01:22 CEST 2016] protected64='eyJub25jZSI6ICJoQVUzMVYtdjhZYk54YlBmNUNVdTRORkx1UDJ6aFFLUldMR0lzbHpYU2drIiwgImFsZyI6ICJSUzI1NiIsICJqd2siOiB7ImUiOiAiQVFBQiIsICJrdHkiOiAiUlNBIiwgIm4iOiAid1dtTGtBbVBhV1Q2QmxPV1JfRDduaVZIX2p0Ti1qRkI5TFp0LXZ0TDFNSDRpLTllOEo3Y2xVTGZ4dWhCZExqU0RBWEdFSmhCZW5lTmFRcWk3WGlULXRGbU9XbUdOTjBmMHMwRjd6ckZVVjdJWEdCaFJodUwzaGoyalNoNzNDcDNXV245aEE2LXRQYmViVWZqY0VMMWJtTGNyV2RUbHlRUG9zQV83T05qVVc3WlloVWxUME1mWER0Yzd2akZ5QklkeWpMMzlzTVZjb01BVXVtWDRYNXhjN2hMa3A4NnZDWFdrV050eFpXeXJHNXcydWZDVkxtWXA2TUg4RC1PZkJiRjBIMmpWT3RJMzlPbjQwS203Y1ZfZURONW82MVEyb0stMWFfWEZTWTBWMWoyRDc3LU1BSFFnUWpEVDlFbkdJcWNTTWdHdTUtWUVFWHV5c3dBQU05aDZ3In19'
[Fr 15. Jul 16:01:22 CEST 2016] sig='duIaVRtPZdAqcgTj5MHNxxqMIealFBkpT9GtyBCtSNxb4DzmOnOPhfVpG59VCRBy3haAbPfz45IUOgn399zIBlh--jUHuwJeHUq8y3e2odO3MHykGUs2-p-k8OHTr4YfKcbYp9wrCOdXTJdq6PLPmS4Qi51xMLoUAke2zBsTPsyz4D1J9vQjDe6inFEZz5hrjZto1IMeB8xx301T-rAgdluouD2meSOsgqZLwkfv-Ydrz_BMG0zRDwT0efNFQfpqhhIaiHTJkEEPbsxXgasLbFo_ZSmm5pN-LQzBuAvv6vNegsR4rsjBk5tYyRFld5EsVKfNkNxa1L85K2pbXdj9EQ'
[Fr 15. Jul 16:01:22 CEST 2016] body='{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "wWmLkAmPaWT6BlOWR_D7niVH_jtN-jFB9LZt-vtL1MH4i-9e8J7clULfxuhBdLjSDAXGEJhBeneNaQqi7XiT-tFmOWmGNN0f0s0F7zrFUV7IXGBhRhuL3hj2jSh73Cp3WWn9hA6-tPbebUfjcEL1bmLcrWdTlyQPosA_7ONjUW7ZYhUlT0MfXDtc7vjFyBIdyjL39sMVcoMAUumX4X5xc7hLkp86vCXWkWNtxZWyrG5w2ufCVLmYp6MH8D-OfBbF0H2jVOtI39On40Km7cV_eDN5o61Q2oK-1a_XFSY0V1j2D77-MAHQgQjDT9EnGIqcSMgGu5-YEEXuyswAAM9h6w"}}, "protected": "eyJub25jZSI6ICJoQVUzMVYtdjhZYk54YlBmNUNVdTRORkx1UDJ6aFFLUldMR0lzbHpYU2drIiwgImFsZyI6ICJSUzI1NiIsICJqd2siOiB7ImUiOiAiQVFBQiIsICJrdHkiOiAiUlNBIiwgIm4iOiAid1dtTGtBbVBhV1Q2QmxPV1JfRDduaVZIX2p0Ti1qRkI5TFp0LXZ0TDFNSDRpLTllOEo3Y2xVTGZ4dWhCZExqU0RBWEdFSmhCZW5lTmFRcWk3WGlULXRGbU9XbUdOTjBmMHMwRjd6ckZVVjdJWEdCaFJodUwzaGoyalNoNzNDcDNXV245aEE2LXRQYmViVWZqY0VMMWJtTGNyV2RUbHlRUG9zQV83T05qVVc3WlloVWxUME1mWER0Yzd2akZ5QklkeWpMMzlzTVZjb01BVXVtWDRYNXhjN2hMa3A4NnZDWFdrV050eFpXeXJHNXcydWZDVkxtWXA2TUg4RC1PZkJiRjBIMmpWT3RJMzlPbjQwS203Y1ZfZURONW82MVEyb0stMWFfWEZTWTBWMWoyRDc3LU1BSFFnUWpEVDlFbkdJcWNTTWdHdTUtWUVFWHV5c3dBQU05aDZ3In19", "payload": "eyJyZXNvdXJjZSI6ICJjaGFsbGVuZ2UiLCAia2V5QXV0aG9yaXphdGlvbiI6ICJqVm9pVlNHTnpJdU5uVVh5Y2R4Ny1kY2ktNGtiNmRaZVRheXBHc1M3c1J3LkYySG9hZTNHaUM0ZVQ4ZDVWams2dnR3eFZsR3praEEtY083R3RiM3luczgifQ", "signature": "duIaVRtPZdAqcgTj5MHNxxqMIealFBkpT9GtyBCtSNxb4DzmOnOPhfVpG59VCRBy3haAbPfz45IUOgn399zIBlh--jUHuwJeHUq8y3e2odO3MHykGUs2-p-k8OHTr4YfKcbYp9wrCOdXTJdq6PLPmS4Qi51xMLoUAke2zBsTPsyz4D1J9vQjDe6inFEZz5hrjZto1IMeB8xx301T-rAgdluouD2meSOsgqZLwkfv-Ydrz_BMG0zRDwT0efNFQfpqhhIaiHTJkEEPbsxXgasLbFo_ZSmm5pN-LQzBuAvv6vNegsR4rsjBk5tYyRFld5EsVKfNkNxa1L85K2pbXdj9EQ"}'
[Fr 15. Jul 16:01:22 CEST 2016] POST
[Fr 15. Jul 16:01:22 CEST 2016] url='https://acme-v01.api.letsencrypt.org/acme/challenge/BhTZROHFCuTBjIi0ZwiP5g-ArE4oIuV4vLbVo0g10B4/176495507'
[Fr 15. Jul 16:01:22 CEST 2016] curl exists=0
[Fr 15. Jul 16:01:22 CEST 2016] _CURL='curl -L --silent --trace-ascii /root/.acme.sh/curl.dump  --dump-header /root/.acme.sh/http.header '
[Fr 15. Jul 16:01:23 CEST 2016] _ret='0'
[Fr 15. Jul 16:01:23 CEST 2016] original='{
  "type": "dns-01",
  "status": "pending",
  "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/BhTZROHFCuTBjIi0ZwiP5g-ArE4oIuV4vLbVo0g10B4/176495507",
  "token": "jVoiVSGNzIuNnUXycdx7-dci-4kb6dZeTaypGsS7sRw",
  "keyAuthorization": "jVoiVSGNzIuNnUXycdx7-dci-4kb6dZeTaypGsS7sRw.F2Hoae3GiC4eT8d5Vjk6vtwxVlGzkhA-cO7Gtb3yns8"
}'
[Fr 15. Jul 16:01:23 CEST 2016] responseHeaders='HTTP/1.1 100 Continue
Expires: Fri, 15 Jul 2016 14:01:23 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache

HTTP/1.1 202 Accepted
Server: nginx
Content-Type: application/json
Content-Length: 334
Boulder-Request-Id: iuhfv-1TiQFSd4IKvJiYDKvmMHuLt4QR3tCwHLLvqsM
Boulder-Requester: 2632158
Link: <https://acme-v01.api.letsencrypt.org/acme/authz/BhTZROHFCuTBjIi0ZwiP5g-ArE4oIuV4vLbVo0g10B4>;rel="up"
Location: https://acme-v01.api.letsencrypt.org/acme/challenge/BhTZROHFCuTBjIi0ZwiP5g-ArE4oIuV4vLbVo0g10B4/176495507
Replay-Nonce: xtyuxYTrUhDvALqtBavNXRfmRywQtR_409p3tHAjsps
Expires: Fri, 15 Jul 2016 14:01:23 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 15 Jul 2016 14:01:23 GMT
Connection: keep-alive
'
[Fr 15. Jul 16:01:23 CEST 2016] response='{"type":"dns-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/BhTZROHFCuTBjIi0ZwiP5g-ArE4oIuV4vLbVo0g10B4/176495507","token":"jVoiVSGNzIuNnUXycdx7-dci-4kb6dZeTaypGsS7sRw","keyAuthorization":"jVoiVSGNzIuNnUXycdx7-dci-4kb6dZeTaypGsS7sRw.F2Hoae3GiC4eT8d5Vjk6vtwxVlGzkhA-cO7Gtb3yns8"}'
[Fr 15. Jul 16:01:23 CEST 2016] code='202'
[Fr 15. Jul 16:01:23 CEST 2016] sleep 5 secs to verify
[Fr 15. Jul 16:01:28 CEST 2016] checking
[Fr 15. Jul 16:01:28 CEST 2016] GET
[Fr 15. Jul 16:01:28 CEST 2016] url='https://acme-v01.api.letsencrypt.org/acme/challenge/BhTZROHFCuTBjIi0ZwiP5g-ArE4oIuV4vLbVo0g10B4/176495507'
[Fr 15. Jul 16:01:28 CEST 2016] curl exists=0
[Fr 15. Jul 16:01:28 CEST 2016] CURL='curl -L --silent --trace-ascii /root/.acme.sh/curl.dump '
[Fr 15. Jul 16:01:28 CEST 2016] ret='0'
[Fr 15. Jul 16:01:28 CEST 2016] original='{
  "type": "dns-01",
  "status": "invalid",
  "error": {
    "type": "urn:acme:error:unauthorized",
    "detail": "Correct value not found for DNS challenge",
    "status": 403
  },
  "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/BhTZROHFCuTBjIi0ZwiP5g-ArE4oIuV4vLbVo0g10B4/176495507",
  "token": "jVoiVSGNzIuNnUXycdx7-dci-4kb6dZeTaypGsS7sRw",
  "keyAuthorization": "jVoiVSGNzIuNnUXycdx7-dci-4kb6dZeTaypGsS7sRw.F2Hoae3GiC4eT8d5Vjk6vtwxVlGzkhA-cO7Gtb3yns8"
}'
[Fr 15. Jul 16:01:28 CEST 2016] response='{"type":"dns-01","status":"invalid","error":{"type":"urn:acme:error:unauthorized","detail":"Correct value not found for DNS challenge","status": 403},"uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/BhTZROHFCuTBjIi0ZwiP5g-ArE4oIuV4vLbVo0g10B4/176495507","token":"jVoiVSGNzIuNnUXycdx7-dci-4kb6dZeTaypGsS7sRw","keyAuthorization":"jVoiVSGNzIuNnUXycdx7-dci-4kb6dZeTaypGsS7sRw.F2Hoae3GiC4eT8d5Vjk6vtwxVlGzkhA-cO7Gtb3yns8"}'
[Fr 15. Jul 16:01:28 CEST 2016] error='"error":{"type":"urn:acme:error:unauthorized","detail":"Correct value not found for DNS challenge","status": 403}'
[Fr 15. Jul 16:01:28 CEST 2016] errordetail='Correct value not found for DNS challenge'
[Fr 15. Jul 16:01:28 CEST 2016] lookup.fail:Verify error:Correct value not found for DNS challenge
[Fr 15. Jul 16:01:28 CEST 2016] Skip for removelevel:
[Fr 15. Jul 16:01:28 CEST 2016] pid`

**Comment by Nosxxx** [comment]
I already change the Key ^^

**Comment by Neilpang** [comment]
@Nosxxx 
So,  is there any problem for you?

**Comment by Nosxxx** [comment]
Yeah im alwas getting: 
[Fr 15. Jul 16:01:28 CEST 2016] errordetail='Correct value not found for DNS challenge'
[Fr 15. Jul 16:01:28 CEST 2016] lookup.fail:Verify error:Correct value not found for DNS challenge

**Comment by Nosxxx** [comment]
Hmm now it works. Strange.

**Comment by Neilpang** [comment]
@Nosxxx 
Can you please open your cloudflare account, and check if the dns txt record is added ?

**Comment by Neilpang** [comment]
@Nosxxx  I guess the txt record doesn't take effect then.
Please add `--dnssleep  180` to wait `180` seconds,  the default is `60`, which may not be enough.

```
acme.sh  --issue  ......  ......   --dns  dns_cf    --dnssleep  180
```

if  *180* is still not enough,  you can increase it. maybe *300*

**Comment by Neilpang** [comment]
@Nosxxx 

I just changed the default dns sleep time from 60 secs to 120 secs.   4a4dacb52cc014776bf6d00419926076b448f72f

It should be much more safer for more common cases.

**Comment by Nosxxx** [comment]
Thanks. I will test it with an other domain ;)

**Comment by Nosxxx** [comment]
Now it works great. Thanks

**Comment by RoliSoft** [comment]
It's possible LetsEncrypt is having issues with DNS validation, since I was consistently getting "wrong value" errors with every client, even though it was properly set. 24 hours later, every client started working again.

So it's probably a (recurring?) temporary issue on their side.

**Comment by Neilpang** [comment]
@RoliSoft 
Correct, it might be.
